Financeiro/Models/bancos_contas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Financeiro.Models
{
    public class bancos_contas
    {
        [Key]
        public int bancos_contas_id { get; set; }  
        [Display(Name ="Descrição")]
        //[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use apenas caracteres alfabéticos.")]
        [StringLength(100,MinimumLength =10,ErrorMessage = "Descrição deve conter mínimo de 10 e máximo 100 caracteres!")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string descricao { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        [Display(Name = "Conta")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Descrição deve conter mínimo de 1 e máximo 20 caracteres!")]
        public string conta { get; set; }       
        [Display(Name = "Agencia")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Descrição deve conter mínimo de 1 e máximo 20 caracteres!")]
        public string agencia { get; set; }
        [Display(Name = "Saldo")]
        public decimal saldo { get; set; }
        [Display(Name = "NIB")]
        public string nib { get; set; }
        [Display(Name = "Swift")]
        public string swift { get; set; }
        [Display(Name = "IBAN")]
        public string iban { get; set; }
        [Display(Name = "Obs")]
        public string obs { get; set; }
        public string apagado { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? dtcadastro { get; set; }
        public int cad_usuario_id { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? dtalteracao { get; set; }
        public int? alt_usuario_id { get; set; }
        public int? apag_usuario_id { get; set; }
        public string status { get; set; }
        public int bancos_id { get; set; }
        public virtual bancos bancos { get; set; }
        public int idtp_conta { get; set; }
        public virtual tp_conta tp_conta { get; set; }
    }
}

Financeiro/Controllers/bancosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Financeiro.Conexao;
using Financeiro.Models;
using PagedList;
using X.PagedList;

namespace Financeiro.Controllers
{
    public class bancosController : Controller
    {
        private Contexto db = new Contexto();

        // GET: bancos
        public  ActionResult Index()
        {
            return View();
        }
           public PartialViewResult Listar(int? pagina, string Buscar)
        {   if(Buscar != null)
            {
                var bancos = db.bancos.Where(b => b.apagado == "N" && b.descricao.Contains(Buscar)).OrderBy(b => b.descricao);
                int paginatamanho = 10;
                int paginaNumero = (pagina ?? 1);
                return PartialView("_Listar", bancos.ToPagedList(paginaNumero, paginatamanho));
            }
        else
            {
                var bancos = db.bancos.Where(b => b.apagado == "N").OrderBy(b => b.descricao);
                int paginatamanho = 10;
                int paginaNumero = (pagina ?? 1);
                return PartialView("_Listar", bancos.ToPagedList(paginaNumero, paginatamanho));
            }
          
           
        }

        // GET: bancos/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // GET: bancos/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: bancos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bancos_id,descricao")] bancos bancos,string form)
        {
           
            
                if (ModelState.IsValid)
                {
                    bancos.apagado = "N";
                    db.bancos.Add(bancos);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return PartialView(bancos);
            

           
        }

        // GET: bancos/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // POST: bancos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bancos_id,descricao")] bancos bancos)
        {
            if (ModelState.IsValid)
            {
                bancos.apagado = "N";
                db.Entry(bancos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bancos);
        }

        // GET: bancos/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // POST: bancos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bancos bancos = await db.bancos.FindAsync(id);
            bancos.apagado = "S";
             db.Entry(bancos).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Financeiro/Controllers/bancos_contasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Financeiro.Conexao;
using Financeiro.Models;
using X.PagedList;
using PagedList;

namespace Financeiro.Controllers
{
    
    public class bancos_contasController : Controller
    { 
    
        private Contexto db = new Contexto();
        static string buscando;
     
        // GET: bancos_contas
        public ActionResult Index(string Buscar, string ativo, string inativo, string op)
        {
     
           
            if (Request.IsAjaxRequest())
            {
             
                if (Buscar is "")
                {
                    buscando = Buscar;
                    if (ativo == "on" && inativo is null)
                    {
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.status == "A").OrderBy(b => b.bancos_contas_id);
                        var bc = bancos_contas;
                        return PartialView("_Listar", bc.ToList());
                    }
                    if(ativo is null && inativo == "on")
                    {
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.status == "I").OrderBy(b => b.bancos_contas_id);
                        
                        return PartialView("_Listar", bancos_contas.ToList());
                    }
                    if(ativo == "on" && inativo == "on")
                    {
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N").OrderBy(b => b.bancos_contas_id);
                        
                        return PartialView("_Listar", bancos_contas.ToList());
                    }
                    else
                    {
                        ViewBag.message = "Verifique sua pesquisa";
                        return PartialView("_Listar");
                    }
                }
                else
                {
                    buscando = Buscar;
                    if (ativo == "on" && inativo is null)
                    {
                      
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.status == "A" && b.descricao.Contains(buscando)).OrderBy(b => b.bancos_contas_id);
                       
                        return PartialView("_Listar",bancos_contas.ToList());
                    }
                    if (ativo is null && inativo == "on")
                    {
                        
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.status == "I" && b.descricao.Contains(buscando)).OrderBy(b => b.bancos_contas_id);
                 
                        return PartialView("_Listar", bancos_contas.ToList());
                    }
                    if (ativo == "on" && inativo == "on")
                    {
                
                        var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.descricao.Contains(buscando)).OrderBy(b => b.bancos_contas_id);
                       
                        return PartialView("_Listar", bancos_contas.ToList());
                    }
                    else
                    {
                        ViewBag.message = "Verifique sua pesquisa";
                        return PartialView("_Listar");
                    }
                   
                }

            }
            else
            {
                var bancos_contas = db.bancos_contas.Include(b => b.bancos).Include(b => b.tp_conta).Where(b => b.apagado == "N" && b.status == "A").OrderBy(b => b.bancos_contas_id);
                return View(bancos_contas.ToList());
            }

                  }
       

        // GET: bancos_contas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos_contas bancos_contas = await db.bancos_contas.FindAsync(id);
            if (bancos_contas == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos_contas);
        }

        // GET: bancos_contas/Create
        public ActionResult Create()
        {
            ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao");
            ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao");
            return PartialView();
        }

        // POST: bancos_contas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bancos_contas_id,descricao,bancos_id,idtp_conta,conta,agencia,nib,swift,iban,obs,apagado,dtcadastro,cad_usuario_id,dtalteracao,alt_usuario_id,apag_usuario_id,status")] bancos_contas bancos_contas)
        {

            bancos_contas.status = "A";
            bancos_contas.apagado = "N";
            if (ModelState.IsValid)
            {
                bancos_contas.dtcadastro = DateTime.Now;
                db.bancos_contas.Add(bancos_contas);
                await db.SaveChangesAsync();
                ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao", bancos_contas.bancos_id);
                ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao", bancos_contas.idtp_conta);
                bancos_contas.descricao = null;
                bancos_contas.agencia = null;
                bancos_contas.conta = null;
                bancos_contas.swift = null;
                bancos_contas.nib = null;
                bancos_contas.iban = null;
                bancos_contas.obs = null;
                return PartialView();
            }

            ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao", bancos_contas.bancos_id);
            ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao", bancos_contas.idtp_conta);
            ViewBag.erro = "erro";
            return PartialView(bancos_contas);
        }

        // GET: bancos_contas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos_contas bancos_contas = await db.bancos_contas.FindAsync(id);
            if (bancos_contas == null)
            {
                return HttpNotFound();
            }
            if(bancos_contas.status == "I")
            {
                ViewBag.inativo = "checked";
            }
            ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao", bancos_contas.bancos_id);
            ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao", bancos_contas.idtp_conta);
            return PartialView(bancos_contas);
        }

        // POST: bancos_contas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bancos_contas_id,descricao,bancos_id,idtp_conta,conta,agencia,saldo,nib,swift,iban,obs,apagado,dtcadastro,cad_usuario_id,dtalteracao,alt_usuario_id,apag_usuario_id,status")] bancos_contas bancos_contas,string inativo)
        {
            if (inativo != "on")
            {
                bancos_contas.status = "A";
                ViewBag.inativo = "";
            }
            if (inativo == "on")
            {
                bancos_contas.status = "I";
                ViewBag.inativo = "checked";
            }
            bancos_contas.apagado = "N";
            if (ModelState.IsValid)
            {
                bancos_contas.dtalteracao = DateTime.Now;
                ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao", bancos_contas.bancos_id);
                ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao", bancos_contas.idtp_conta);
                db.Entry(bancos_contas).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return PartialView();
            }
            ViewBag.bancos_id = new SelectList(db.bancos, "bancos_id", "descricao", bancos_contas.bancos_id);
            ViewBag.idtp_conta = new SelectList(db.tp_conta, "idtp_conta", "descricao", bancos_contas.idtp_conta);
            return View(bancos_contas);
        }

        // GET: bancos_contas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos_contas bancos_contas = await db.bancos_contas.FindAsync(id);
            if (bancos_contas == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos_contas);
         
        }

        // POST: bancos_contas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bancos_contas bancos_contas = await db.bancos_contas.FindAsync(id);
            bancos_contas.apagado = "S";

Financeiro/Views/bancos_contas/Create - Cópia .cshtml
@model Financeiro.Models.bancos_contas

<div class="row">
    <div class="col-md-12">
        <h4><span class="fa fa-money"></span> Cadastro de novas contas</h4>
        @using (Html.BeginForm(FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-row border-white border corformverde">
                <div class="form-group col-md-6 form-row">
                    <div class="col-md-12 p-0">
                        <label class=" col-form-label col-form-label-sm col-sm-10">Descrição</label>
                        <div class="col-sm-12  col-md-12 col-lg-12 col-12 col-xl-12">
                            @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control form-control-sm col-sm-12 col-12 col-md-12 col-lg-12 col-xl-9", @placeholder = "Nome da conta" } })
                            @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">Banco</label>
                        <div class="col-sm-12 ">
                            @Html.DropDownList("bancos_id", null, htmlAttributes: new { @class = "form-control form-control-sm col-10 col-lg-10 col-md-10 col-xl-6 col-sm-10 col-12" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">Tipo de conta</label>
                        <div class="col-sm-12 ">
                            @Html.DropDownList("idtp_conta", null, htmlAttributes: new { @class = "form-control form-control-sm col-lg-10 col-10 col-sm-10 col-md-10 col-xl-6 col-12" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">Conta</label>
                        <div class="col-sm-12  col-12">
                            @Html.EditorFor(model => model.conta, new { htmlAttributes = new { @class = "form-control form-control-sm col-xl-3 col-sm-5 col-md-6 col-lg-4 col-12", @placeholder = "Conta" } })
                            @Html.ValidationMessageFor(model => model.conta, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">Agencia</label>
                        <div class="col-sm-12 ">
                            @Html.EditorFor(model => model.agencia, new { htmlAttributes = new { @class = "form-control form-control-sm col-xl-3 col-sm-5 col-md-6 col-lg-4 col-12", @placeholder = "Agencia" } })
                            @Html.ValidationMessageFor(model => model.agencia, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                    </div>
                </div>
                <div class="form-group form-row col-md-6">
                    <div class="col-md-12">
                        <label class="col-form-label col-form-label-sm  col-sm-10">NIB</label>
                        <div class="col-sm-12 ">
                            @Html.EditorFor(model => model.nib, new { htmlAttributes = new { @class = "form-control form-control-sm col-xl-3 col-sm-5 col-md-6 col-lg-4 col-12", @placeholder = "Nib" } })
                            @Html.ValidationMessageFor(model => model.nib, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">Swift</label>
                        <div class="col-sm-12 ">
                            @Html.EditorFor(model => model.swift, new { htmlAttributes = new { @class = "form-control form-control-sm col-xl-3 col-5 col-sm-5 col-md-6 col-lg-4 col-12", @placeholder = "Swift" } })
                            @Html.ValidationMessageFor(model => model.swift, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                        <label class="col-form-label col-form-label-sm  col-sm-10">IBAN</label>
                        <div class="col-sm-12 ">
                            @Html.EditorFor(model => model.iban, new { htmlAttributes = new { @class = "form-control form-control-sm col-xl-3 col-5 col-sm-5 col-md-6 col-lg-4 col-12", @placeholder = "Iban" } })
                            @Html.ValidationMessageFor(model => model.iban, "", new { @class = "text-danger col-form-label-sm" })
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-sm-2 col-form-label   col-form-label-sm">Obs</label>
                    <div class="col-sm-12">
                        @Html.TextAreaFor(model => model.obs, htmlAttributes: new { @class = "form-control col-12", @placeholder = "Digite aqui as observações da sua conta" })
                        @Html.ValidationMessageFor(model => model.obs, "", new { @class = "text-danger col-form-label-sm" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-sm-2 col-form-label   col-form-label-sm">Opções</label>
                    <div class="col-sm-12">
                        <a href="@Url.Action("Index","bancos")" target="_blank" class="btn btn-warning btndetalhes btn-sm" id="btnnovo" data-toggle="tooltip" data-placement="top" title="Novo Banco">
                            <span class="fa fa-plus"></span> Novo Banco
                        </a>
                        <a href="@Url.Action("Index","tp_conta")" target="_blank" class="btn btn-warning btndetalhes btn-sm" id="btnnovo" data-toggle="tooltip" data-placement="top" title="Novo Banco">
                            <span class="fa fa-plus"></span> Novo tipo de conta
                        </a>
                    </div>
                </div>
                <div class="form-group col-12 text-right">
                    <div class="col-md-offset-2 col-md-12">
                        <button class="btn btn-sm btn-primary"><span class="fa fa-save"></span> Salvar</button>
                        <a class="btn btn-sm btn-danger" href="@Url.Action("Index")"><span class="fa fa-sign-out"></span> Sair</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="modal fade" data-backdrop="static" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="teste">
            
        </div>
    </div>
</div>
<div id="lista">
    teste
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
           
            $("#btnnovaconta").click(function () {
                var form = "1";
                    $("#teste").load("@Url.Action("Index","tp_conta")",
                        function () {
                       $("#exampleModalCenter").modal("show");
                      }
                   );

            });

            $("#btnnovotpc").click(function () {
                $("#lista").remove();
            });


            });
    </script>
}

Financeiro/Views/bancos_contas/Delete.cshtml
@model Financeiro.Models.bancos_contas
<div class="modal-header p-2">
    <h5 class="modal-title m-1">Deletar conta</h5>
    <button type="button" class="close" data-dismiss="modal">
        <span class="fa fa-close" style="color:red"></span>
    </button>
</div>

<div class="modal-body ">

    <a style="text-align:center;color:black">Deseja realmente deletar essa conta?</a>
</div>
<div class="modal-footer p-2">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions m-1 no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
        </div>
    }

</div>

Financeiro/Views/bancos_contas/Details.cshtml
@model Financeiro.Models.bancos_contas
<div class="modal-header">
    <h5 class="modal-title">Destalhes da conta</h5>
    <button type="button" class="close" data-dismiss="modal">
        <span class="fa fa-close" style="color:crimson"></span>
    </button>
</div>
<div class="modal-body">
    <div >
        <div class="">
            <b>@Html.DisplayNameFor(model => model.descricao):</b>
            @Html.DisplayFor(model => model.descricao)
            @if (Model.status == "I")
            {

                <B style="float:right;color:crimson">Inativo</B>

            }
            @if (Model.status == "A")
            {

                <B style="float:right; color:green">Ativa</B>

            }
        </div>
        <div class="">
            <b>@Html.DisplayNameFor(model => model.bancos.descricao):</b>
            @Html.DisplayFor(model => model.bancos.descricao)
        </div>
        <div>
            <b>@Html.DisplayNameFor(model => model.tp_conta.descricao):</b>
            @Html.DisplayFor(model => model.tp_conta.descricao)
            <b>@Html.DisplayNameFor(model => model.agencia):</b>
            @Html.DisplayFor(model => model.agencia)
            <b> @Html.DisplayNameFor(model => model.conta):</b>
            @Html.DisplayFor(model => model.conta)
        </div>
        <div class="">
            <b>@Html.DisplayNameFor(model => model.nib):</b>
            @Html.DisplayFor(model => model.nib)
        </div>
        <div>
            <b>@Html.DisplayNameFor(model => model.iban):</b>
            @Html.DisplayFor(model => model.iban)
        </div>
        <div>
            <b> @Html.DisplayNameFor(model => model.swift):</b>
            @Html.DisplayFor(model => model.swift)
        </div>
        <div>
            <b> @Html.DisplayNameFor(model => model.obs):</b>
            @Html.DisplayFor(model => model.obs)
        </div>
        <div style="text-align:right">
            <b> @Html.DisplayNameFor(model => model.saldo):</b>
            @Html.DisplayFor(model => model.saldo)
        </div>
    </div>
</div>
<div class="modal-footer">
    <div align="right">
        <a class="btn btn-primary btn-sm" href="@Url.Action("Edit","bancos_contas",new { id = Model.bancos_contas_id })" data-toggle="tooltip" data-placement="top" title="Editar"><span class="fa fa-pencil"></span> Editar</a>
    </div>
</div>

Financeiro/Views/bancos_contas/Index.old.cshtml
@model PagedList.IPagedList<Financeiro.Models.bancos_contas>
@using PagedList;
@using PagedList.Mvc;
<h4><span class="fa fa-money"></span> Contas Bancarias</h4>
<div class="row">
    <div class="col-md-6 col-9">
        @using (Html.BeginForm())
        {
            <div class="form-inline m-1">
                <div class="input-group row col-12 col-md-7">
                    <input type="text" class="form-control form-control-sm" id="Buscar" name="Buscar" placeholder="Nome da conta">
                    <div class="input-group-append">
                        <input type="submit" value="Pesquisar" id="Pesquisar" class="btn btn-default btn-sm" />
                    </div>
                </div>
                <div class="custom-control custom-checkbox m-1 custom-control-inline">
                    <input type="checkbox" class="custom-control-input" id="customCheck1" name="ativo" @ViewBag.ativo>
                    <label class="custom-control-label" for="customCheck1">ativo</label>
                </div>
                <div class="custom-control custom-checkbox m-1 custom-control-inline">
                    <input type="checkbox" class="custom-control-input" id="customCheck2" name="inativo" @ViewBag.inativo>
                    <label class="custom-control-label" for="customCheck2">inativo</label>
                </div>
            </div>
        }

    </div>

    <div class="col-md-6 text-right col-3">
        <a href="@Url.Action("Create","bancos_contas")" class="btn btn-sm btn-primary m-1"><span class="fa fa-plus"></span> Adicionar conta</a>
    </div>
    <div class="col-md-12" id="listaconta">
        @Html.Action("Listar")
    </div>
    <div class="modal fade" data-backdrop="static" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="teste">

            </div>
        </div>
    </div>

    @section scripts{
        <script type="text/javascript">
            $(document).ready(function () {

                $('#btnsair').click(limpar);
                function limpar() {
                    $('#teste2').html('');
                }

                $(".btndetalhes").click(function () {
                    var id = $(this).data("value");
                    $("#teste").load("/bancos_contas/Details/" + id,
                        function () {
                            $("#exampleModalCenter").modal("show");
                        }
                    );

                });
                $(".btndelete").click(function () {
                    var id = $(this).data("value");
                    $("#teste").load("/bancos_contas/Delete/" + id,
                        function () {
                            $("#exampleModalCenter").modal("show");
                        }
                    );

                });


                //$(".btnnovo").click(function () {
                // $("#teste2").load("",
                // function () {
                //  $("#exampleModalCenter").modal("show");
                // }
                // );

                //});

            });</script>
    }