Financeiro/Controllers/bancosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Financeiro.Conexao;
using Financeiro.Models;
using PagedList;
using X.PagedList;

namespace Financeiro.Controllers
{
    public class bancosController : Controller
    {
        private Contexto db = new Contexto();

        // GET: bancos
        public  ActionResult Index()
        {
            return View();
        }
           public PartialViewResult Listar(int? pagina, string Buscar)
        {   if(Buscar != null)
            {
                var bancos = db.bancos.Where(b => b.apagado == "N" && b.descricao.Contains(Buscar)).OrderBy(b => b.descricao);
                int paginatamanho = 10;
                int paginaNumero = (pagina ?? 1);
                return PartialView("_Listar", bancos.ToPagedList(paginaNumero, paginatamanho));
            }
        else
            {
                var bancos = db.bancos.Where(b => b.apagado == "N").OrderBy(b => b.descricao);
                int paginatamanho = 10;
                int paginaNumero = (pagina ?? 1);
                return PartialView("_Listar", bancos.ToPagedList(paginaNumero, paginatamanho));
            }
          
           
        }

        // GET: bancos/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // GET: bancos/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: bancos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bancos_id,descricao")] bancos bancos,string form)
        {
           
            
                if (ModelState.IsValid)
                {
                    bancos.apagado = "N";
                    db.bancos.Add(bancos);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return PartialView(bancos);
            

           
        }

        // GET: bancos/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // POST: bancos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bancos_id,descricao")] bancos bancos)
        {
            if (ModelState.IsValid)
            {
                bancos.apagado = "N";
                db.Entry(bancos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bancos);
        }

        // GET: bancos/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bancos bancos = await db.bancos.FindAsync(id);
            if (bancos == null)
            {
                return HttpNotFound();
            }
            return PartialView(bancos);
        }

        // POST: bancos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bancos bancos = await db.bancos.FindAsync(id);
            bancos.apagado = "S";
             db.Entry(bancos).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Financeiro/Controllers/layoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financeiro.Controllers
{
    public class layoutController : Controller
    {
        // GET: layout
        public ActionResult Index()
        {
            return View();
        }
    }
}

Financeiro/Controllers/pl_d_contasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Financeiro.Conexao;
using Financeiro.Models;

namespace Financeiro.Controllers
{
    public class pl_d_contasController : Controller
    {
        private Contexto db = new Contexto();

        // GET: pl_d_contas
        public async Task<ActionResult> Index()
        {
            return View(await db.pl_d_contas.ToListAsync());
        }

        // GET: pl_d_contas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pl_d_contas pl_d_contas = await db.pl_d_contas.FindAsync(id);
            if (pl_d_contas == null)
            {
                return HttpNotFound();
            }
            return View(pl_d_contas);
        }

        // GET: pl_d_contas/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: pl_d_contas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idpl_d_contas,planoContas")] pl_d_contas pl_d_contas)
        {
            if (ModelState.IsValid)
            {
                db.pl_d_contas.Add(pl_d_contas);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return PartialView(pl_d_contas);
        }

        // GET: pl_d_contas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pl_d_contas pl_d_contas = await db.pl_d_contas.FindAsync(id);
            if (pl_d_contas == null)
            {
                return HttpNotFound();
            }
            return PartialView(pl_d_contas);
        }

        // POST: pl_d_contas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idpl_d_contas,planoContas")] pl_d_contas pl_d_contas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pl_d_contas).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return PartialView(pl_d_contas);
        }

        // GET: pl_d_contas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pl_d_contas pl_d_contas = await db.pl_d_contas.FindAsync(id);
            if (pl_d_contas == null)
            {
                return HttpNotFound();
            }
            return PartialView(pl_d_contas);
        }

        // POST: pl_d_contas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            pl_d_contas pl_d_contas = await db.pl_d_contas.FindAsync(id);
            db.pl_d_contas.Remove(pl_d_contas);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Financeiro/Controllers/tp_contaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Financeiro.Conexao;
using Financeiro.Models;

namespace Financeiro.Controllers
{
    public class tp_contaController : Controller
    {
        private Contexto db = new Contexto();

        // GET: tp_conta
        public async Task<ActionResult> Index()
        {
            return PartialView(await db.tp_conta.ToListAsync());
        }

        // GET: tp_conta/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tp_conta tp_conta = await db.tp_conta.FindAsync(id);
            if (tp_conta == null)
            {
                return HttpNotFound();
            }
            return PartialView(tp_conta);
        }

        // GET: tp_conta/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: tp_conta/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idtp_conta,descricao,fundos,investimento")] tp_conta tp_conta)
        {
            if (ModelState.IsValid)
            {
                db.tp_conta.Add(tp_conta);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(tp_conta);
        }

        // GET: tp_conta/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tp_conta tp_conta = await db.tp_conta.FindAsync(id);
            if (tp_conta == null)
            {
                return HttpNotFound();
            }
            return PartialView(tp_conta);
        }

        // POST: tp_conta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idtp_conta,descricao,fundos,investimento")] tp_conta tp_conta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tp_conta).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tp_conta);
        }

        // GET: tp_conta/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tp_conta tp_conta = await db.tp_conta.FindAsync(id);
            if (tp_conta == null)
            {
                return HttpNotFound();
            }
            return PartialView(tp_conta);
        }

        // POST: tp_conta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            tp_conta tp_conta = await db.tp_conta.FindAsync(id);
            db.tp_conta.Remove(tp_conta);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Financeiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Financeiro</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" />
</head>
<body class="pingendo-light">
    <nav class="navbar fontmedia navbar-expand-lg navbar-dark  navbar-dark pigendo-secundary fixed-top text-light">
        <a class="navbar-brand"><span class="fa fa-money"></span> Financeiro</a>
        <button class="navbar-toggler navbar-dark " type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Home")">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                    <div class="dropdown-menu dropright" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item dropdown-toggle " href="#" id="contas" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contas</a>
                        <div class="dropdown-menu" aria-labelledby="contas">
                            <a class="dropdown-item" href="@Url.Action("Index","bancos_contas")">Contas Correntes</a>
                            <a class="dropdown-item" href="@Url.Action("Index","bancos")">Bancos</a>
                            <a class="dropdown-item" href="@Url.Action("Index","tp_conta")">Tipo de contas</a>
                            <a class="dropdown-item" href="@Url.Action("Index","pl_d_contas")">Plano de contas</a>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index","bancos")">Classificação</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About","Home")">Sobre</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact","Home")">Contatos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " id="hora" style="text-align:right">hora</a>
                </li>
            </ul>
        </div>
    </nav>
    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>-->
    <p></p>
    <div class="container-fluid body-content">
            @RenderBody()
        </div>
    <p>

    </p>
        <div>
            <footer>
                <p style="text-align:center"> Copyright&copy; @DateTime.Now.Year - José Mario Vieira</p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/inputmask")
        @RenderSection("scripts", required: false)
</body>
</html>